CREATE TABLE IF NOT EXISTS danmu (
  id bigserial PRIMARY KEY,
  vid INTEGER NOT NULL,
  uid INTEGER NOT NULL,
  content VARCHAR(100) NOT NULL,
  fontsize SMALLINT NOT NULL DEFAULT 25,
  mode SMALLINT NOT NULL DEFAULT 1,
  color VARCHAR(7) NOT NULL DEFAULT '#FFFFFF',
  time_point DOUBLE PRECISION NOT NULL,
  state SMALLINT NOT NULL DEFAULT 1,
  create_date TIMESTAMP NOT NULL
);
